apiVersion: policy.kubevault.com/v1alpha1
kind: VaultPolicy
metadata:
  name: demo-policy-secret-reader
  namespace: demo
spec:
  vaultRef:
    name: vault-app
  policyDocument: |
    path "secret/*" {
      capabilities = ["read", "list"]
    }
