apiVersion: v1alpha1
kind: Cluster
metadata:
  creationTimestamp: 2017-10-09T10:00:38Z
  generation: 1507543238411839897
  name: digital2
  uid: ACID-K8S-C-rlghv6vki5gfuha
spec:
  api:
    advertiseAddress: ""
    bindPort: 6443
  caCertName: ca
  cloud:
    cloudProvider: digitalocean
    instanceImage: ubuntu-16-04-x64
    region: nyc3
    zone: nyc3
  credentialName: do
  frontProxyCACertName: front-proxy-ca
  kubernetesVersion: v1.9.0
  networking:
    networkProvider: calico
    nonMasqueradeCIDR: 10.0.0.0/8
status:
  apiServer:
  - address: 10.132.70.110
    type: InternalIP
  - address: 159.203.122.109
    type: ExternalIP
  cloud: {}
  phase: Ready
  sshKeyExternalID: d1-ssddan