apiVersion: policy.kubevault.com/v1alpha1
kind: VaultPolicy
metadata:
  name: read-only-policy
  namespace: demo
spec:
  vaultRef:
    name: vault
  policyDocument: |
    path "sys/policy" {
      capabilities = ["list"]
    }

    path "sys/policy/*" {
      capabilities = ["read"]
    }