apiVersion: v1
kind: Service
metadata:
  name: vault
  namespace: default
spec:
  ports:
  - name: http
    nodePort: 30001
    port: 8200
  selector:
    app: vault
  type: NodePort
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vault
  namespace: default
  labels:
    app: vault
spec:
  serviceName: "vault"
  selector:
    matchLabels:
      app: vault
  replicas: 1
  template:
    metadata:
      labels:
        app: vault
    spec:
      containers:
      - name: vault
        image: "vault:1.0.0"
        args:
        - "server"
        - "-dev"
        - "-dev-root-token-id=aajf-dhg-ddht-ccdf"
        ports:
        - name: http
          containerPort: 8200
          protocol: "TCP"
        - name: server
          containerPort: 8201
          protocol: "TCP"
